### ISSUE TITLE
Need to get job duration value from addjob.php

### ISSUE THREAD

**Issue by tomble21** [Mattw46/CPT375-A2#20]
I'm having trouble POSTing the job duration value.  Correct me if I'm wrong, but the value is populated using jquery.  Anyone know how we can easily grab the value and POST it? Naming the element didn't work.
Currently hardcoded as 3.  Other than this, we can now add a job :)

**Comment by bourkg** [comment]
Was implementing postjob as the same time as you before noticing that you were already after committing a solution. We probably need to e-mail each other on what parts we are going to work to prevent overlap. But I was having the same issue as you. I was not able to get job duration. 

Was also working on the db insert as it was returning error. Hopefully Jalal will be able to help

**Comment by jalalhobbs** [comment]
Updated /php/compontents/content/addjob.php to include a hidden input with a default value matching the slider.
Updated /javascript/javascript.js to make the hidden value be updated upon slider update.

Should post as 'joblength'
