### ISSUE TITLE
Populate userdetails page

### ISSUE THREAD

**Issue by tomble21** [Mattw46/CPT375-A2#21]
Hey guys, this is what I'm going to be working on tonight.  I'm going to try and create a branch to do it, to keep the model and controller intact.  
Let me know asap if you're already working on this.
Pete

**Comment by tomble21** [comment]
Sorry, I stuffed up the branch and committed to master.  I've figured out how to do it properly now, I think.

**Comment by bourkg** [comment]
Not sure if we really need to do branch's....I'm only learning git also. What I've seen is if there are github is ahead of local level it will not allow you to push. You will need to pull. I will allow you to pull if there are no conflicts. You can then push to master. Not sure what to do if conflicts are encountered. Maybe someone else can comment

**Comment by Mattw46** [comment]
When there is a conflict I usually take a copy the run
Git --reset head
Got pull

Then copy your changes to the newly downloaded copy
